### purchase
POST localhost:8080/items/5/purchase
Content-Type: application/json

### Top 10
GET localhost:8080/items/ranks
Content-Type: application/json

### Cache - readOne
GET localhost:8080/items/1
Content-Type: application/json

### Cache - readAll
GET localhost:8080/items
Content-Type: application/json

### Cache - create
POST localhost:8080/items
Content-Type: application/json

{
  "name": "test mouse",
  "description": "test mouse description",
  "price": "100000"
}

### Cache - update
PUT localhost:8080/items/1
Content-Type: application/json

{
  "price": 10000
}